[package]
name = "rust_async_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
executor = { git = "https://github.com/DeathWish5/executor.git" }
uart_16550 = "0.2.16"